# Generated by Django 4.1.3 on 2022-12-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_employee_salary_employ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='employ',
            new_name='employee',
        ),
    ]
