# Generated by Django 4.1.3 on 2022-12-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_rename_employ_salary_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
