# Generated by Django 4.1.3 on 2022-12-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_salary_employee_delete_employee_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
